In [31]:
from mxnet import nd,autograd

In [7]:
x = nd.arange(12)

In [8]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [9]:
x.shape

(12,)

In [10]:
x.size

12

In [14]:
x=x.reshape((3,4))

In [15]:
y=nd.random.normal(0,1,shape=(3,4))

In [16]:
x+y


[[ 0.5035904  -0.18944502  1.4497862   1.4081243 ]
 [ 2.8918052   5.07872     5.0814366   6.254286  ]
 [ 6.791914   10.814021    8.477257    8.484755  ]]
<NDArray 3x4 @cpu(0)>

In [17]:
x *y


[[  0.          -1.189445    -1.1004275   -4.775627  ]
 [ -4.432779     0.39360103  -5.5113807   -5.2200007 ]
 [ -9.66469     16.32619    -15.22743    -27.667694  ]]
<NDArray 3x4 @cpu(0)>

In [18]:
x/y


[[ 0.        -0.8407282 -3.6349509 -1.8845693]
 [-3.609474  63.516094  -6.5319386 -9.386972 ]
 [-6.6220436  4.9613533 -6.567096  -4.3733315]]
<NDArray 3x4 @cpu(0)>

In [19]:
x.exp()


[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02 1.0966332e+03]
 [2.9809580e+03 8.1030840e+03 2.2026465e+04 5.9874141e+04]]
<NDArray 3x4 @cpu(0)>

In [20]:
nd.dot(x,y.T)


[[ -7.0655     -3.9955497  -8.7772   ]
 [-18.377275  -14.770558  -22.505411 ]
 [-29.68905   -25.545568  -36.233624 ]]
<NDArray 3x3 @cpu(0)>

In [21]:
nd.concat(x,y,dim=0)


[[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [ 0.5035904  -1.189445   -0.55021375 -1.5918757 ]
 [-1.1081947   0.0787202  -0.9185634  -0.74571437]
 [-1.2080863   1.8140212  -1.522743   -2.515245  ]]
<NDArray 6x4 @cpu(0)>

In [30]:
x>y


[[0. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [23]:
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [24]:
nd.norm(x)


[22.494442]
<NDArray 1 @cpu(0)>

In [25]:
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [28]:
x[:,1:]


[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 9. 10. 11.]]
<NDArray 3x3 @cpu(0)>